public with sharing class CheckforRecrussion {
    
      Public static Boolean  isRecrussion = false;
      Public static Boolean  isRTFUpdate  = false;
       Public static Boolean  chkApproveOrnot  = false;
      Public static Boolean  isRdd  = false;
      // static boolean 
    	
     public static Boolean isInf = false;
     public static Boolean isCon = false;
     public static Boolean isRes = false;
     public static Boolean isInfRemove = false;
     public static Boolean isConRemove = false;
     public static Boolean isResRemove = false;

}