<http://linkedjazz.org/resource/William_D_Simone> <http://xmlns.com/foaf/0.1/name> "William D. Simone"@en .
<http://dbpedia.org/resource/Louis_Armstrong> <http://xmlns.com/foaf/0.1/name> "Louis Armstrong"@en .
<http://dbpedia.org/resource/Mel_Brooks> <http://xmlns.com/foaf/0.1/name> "Mel Brooks"@en .
<http://dbpedia.org/resource/Joe_Marsala> <http://xmlns.com/foaf/0.1/name> "Joe Marsala"@en .
<http://dbpedia.org/resource/Freddie_Hubbard> <http://xmlns.com/foaf/0.1/name> "Freddie Hubbard"@en .
<http://id.loc.gov/authorities/names/no99050719> <http://xmlns.com/foaf/0.1/name> "Howard Biggs"@en .
<http://dbpedia.org/resource/Andrew_Cyrille> <http://xmlns.com/foaf/0.1/name> "Andrew Cyrille"@en .
<http://dbpedia.org/resource/Maceo_Parker> <http://xmlns.com/foaf/0.1/name> "Maceo Parker"@en .
<http://linkedjazz.org/resource/Joseph_Thomas> <http://xmlns.com/foaf/0.1/name> "Joseph Thomas"@en .
<http://musicbrainz.org/artist/4a217cd8-6019-47c6-a29f-c77de82ddadc> <http://xmlns.com/foaf/0.1/name> "Piney Brown"@en .
<http://linkedjazz.org/resource/Billy_Krechmer> <http://xmlns.com/foaf/0.1/name> "Billy Krechmer"@en .
<http://id.loc.gov/authorities/names/n83056867> <http://xmlns.com/foaf/0.1/name> "Kenny Durham"@en .
<http://dbpedia.org/resource/Ralph_Gleason> <http://xmlns.com/foaf/0.1/name> "Ralph Gleason"@en .
<http://linkedjazz.org/resource/Jimmy_Evans> <http://xmlns.com/foaf/0.1/name> "Jimmy Evans"@en .
<http://linkedjazz.org/resource/Johnny_Johanna_(singer)> <http://xmlns.com/foaf/0.1/name> "Johnny Johanna"@en .
<http://linkedjazz.org/resource/Father_Peter_OBrien> <http://xmlns.com/foaf/0.1/name> "Father Peter O&#039;Brien"@en .
<http://id.loc.gov/authorities/names/no2006090173.html> <http://xmlns.com/foaf/0.1/name> "Sam Reed"@en .
<http://dbpedia.org/resource/Ray_Nance> <http://xmlns.com/foaf/0.1/name> "Ray Nance"@en .
<http://dbpedia.org/resource/Harold_Ousley> <http://xmlns.com/foaf/0.1/name> "Harold Ousley"@en .
<http://dbpedia.org/resource/Kenny_Kirkland> <http://xmlns.com/foaf/0.1/name> "Kenny Kirkland"@en .
<http://dbpedia.org/resource/Clarence_Williams_(musician)> <http://xmlns.com/foaf/0.1/name> "Clarence Williams"@en .
<http://linkedjazz.org/resource/Trevor_Feldman_drummer> <http://xmlns.com/foaf/0.1/name> "Trevor Feldman"@en .
<http://id.loc.gov/authorities/names/no2007044827> <http://xmlns.com/foaf/0.1/name> "Teddy Stewart"@en .
<http://dbpedia.org/resource/Frank_Wess> <http://xmlns.com/foaf/0.1/name> "Frank Wess"@en .